Repository umdio/umdio, pull requests merged in 2021-04, with the labels that each got.

#177 Improve rakefile/readme
  README.md
  Rakefile
  app/scrapers/map_scraper.rb
Labels: enhancement

#189 Only run CI when code is touched
  .github/workflows/main.yml
Labels: enhancement

#188 Added dev:up and dev:down commands
  README.md
  Rakefile
Labels: enhancement

#173 Scraper bug fixes
  .solargraph.yml
  Gemfile
  README.md
  Rakefile
  app/models/bus.rb
  app/scrapers/courses_scraper.rb
  app/scrapers/majors_scraper.rb
  app/scrapers/scraper_common.rb
  app/scrapers/sections_scraper.rb
  openapi.yaml
  server.rb
Labels: Code Health, bug, scraper

#179 adhere to basic robocop style
  Gemfile
  Motivations.md
  README.md
  Rakefile
  app/controllers/bus_controller.rb
  app/controllers/courses_controller.rb
  app/controllers/majors_controller.rb
  app/controllers/map_controller.rb
  app/controllers/professors_controller.rb
  app/controllers/root_controller.rb
  app/helpers/bus_helpers.rb
  app/helpers/courses_helpers.rb
  app/helpers/errors.rb
  app/helpers/helpers.rb
  app/helpers/map_helpers.rb
  app/helpers/requests.rb
  app/helpers/string.rb
  app/models/building.rb
  app/models/bus.rb
  app/models/courses.rb
  app/models/majors.rb
  app/scrapers/bus_routes_scraper.rb
  app/scrapers/bus_schedules_scraper.rb
  app/scrapers/courses_importer.rb
  app/scrapers/courses_scraper.rb
  app/scrapers/majors_scraper.rb
  app/scrapers/map_scraper.rb
  app/scrapers/scraper_common.rb
  app/scrapers/sections_scraper.rb
  server.rb
  tests/helper_spec.rb
  tests/root_spec.rb
  tests/spec_helper.rb
  tests/v0/buses_spec.rb
  tests/v0/courses/courses_spec.rb
  tests/v0/courses/pagination_spec.rb
  tests/v0/majors_spec.rb
  tests/v0/map_spec.rb
  tests/v0/professors_spec.rb
  tests/v1/buses_spec.rb
  tests/v1/courses/courses_spec.rb
  tests/v1/courses/pagination_spec.rb
  tests/v1/majors_spec.rb
  tests/v1/map_spec.rb
  tests/v1/professors_spec.rb
Labels: Code Health, enhancement

#193 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/endpoint_request.md
Labels: Code Health

#205 Development changes made in #194
  Gemfile
  docker-compose-dev.yml
  docker-compose.yml
  openapi.yaml
Labels: Code Health, docs

#206 Added openapi spec validation to validate task
  Rakefile
Labels: Code Health

#207 Added Rubocop (Again)
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Rakefile
Labels: Code Health

#194 Added tests to scraper_common and majors_scraper
  .gitignore
  Gemfile
  Rakefile
  app/helpers/helpers.rb
  app/scrapers/majors_scraper.rb
  app/scrapers/scraper_common.rb
  openapi.yaml
  tests/helper_spec.rb
  tests/root_spec.rb
  tests/scrapers/majors_scraper_spec.rb
  tests/scrapers/scraper_common_spec.rb
  tests/v1/buses_spec.rb
  tests/v1/courses/courses_spec.rb
  tests/v1/courses/pagination_spec.rb
  tests/v1/majors_spec.rb
  tests/v1/map_spec.rb
  tests/v1/professors_spec.rb
Labels: Code Health, enhancement, help wanted, scraper
